export const CHANGE_TEMPERATURE_AT_ROOM = '@@ROOMS/CHANGE_TEMPERATURE_AT_ROOM';
export const CHOOSE_IMAGE_GALLERY_ITEM = '@@ROOMS/CHOOSE_IMAGE_GALLERY_ITEM';
export const CHANGE_HUMIDITY_AT_ROOM = '@@ROOMS/CHANGE_HUMIDITY_AT_ROOM';
export const EDIT_DATA_AT_ROOM = '@@ROOMS/EDIT_DATA_AT_ROOM';
export const BIND_COOLERS_TO_ROOM = '@@ROOMS/BIND_COOLERS_TO_ROOM';
export const SAVE_COOLERS = '@@ROOMS/SAVE_COOLERS';
export const EDIT_EVENT_FOR_ROOM = '@@ROOMS/EDIT_EVENT_FOR_ROOM';
export const CREATE_EVENT_FOR_ROOM = '@@ROOMS/CREATE_EVENT_FOR_ROOM';
