export const CHANGE_TEMPERATURE_AT_ROOM = '@@ROOMS/CHANGE_TEMPERATURE_AT_ROOM';
export const CHOOSE_IMAGE_GALLERY_ITEM = '@@ROOMS/CHOOSE_IMAGE_GALLERY_ITEM';
export const CHANGE_HUMIDITY_AT_ROOM = '@@ROOMS/CHANGE_HUMIDITY_AT_ROOM';
export const EDIT_DATA_AT_ROOM = '@@ROOMS/EDIT_DATA_AT_ROOM';
